name: Publish NPM Package
on:
  push:
    branches:
      - master

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

jobs:
  publish_npm_package_and_create_release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish NPM Package
        run: npm publish