name: Publish NPM Package and Create Release
on:
  push:
    branches:
      - master

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

jobs:
  publish_npm_package_and_create_release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish NPM Package
        run: npm publish

      - name: Create Tag
        run: |
          git tag "v${{ env.npm_package_version }}"
          git push origin "v${{ env.npm_package_version }}"

      - name: Print version from package.json
        run: echo "v${{ env.npm_package_version }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.npm_package_version }}"
          release_name: "Release v${{ env.npm_package_version }}"
          body: |
            - See the package to download this version.
          draft: false
          prerelease: true
          projectPath: dist