name: Release
on:
  push:
    branches:
      - master

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      # Create Release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.npm_package_version }}
          release_name: Release ${{ env.npm_package_version }}
          body: |
            Release ${{ env.npm_package_version }}
          draft: false
          prerelease: false

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish
