name: NPM Package Release
on: push

env:
  NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          package_folder: './dist'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}